In [5]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.metrics import confusion_matrix, multilabel_confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.multioutput import MultiOutputClassifier

# Load Datasets

In [6]:
def load_data(file_path):
    A = np.loadtxt(file_path)
    X = A[:, :9]    # Input features
    y = A[:, 9:]    # Output labels
    return X, y

In [7]:
# Load all 3 datasets
X_final, y_final = load_data('data/tictac_final.txt')
y_final = y_final[:, 0]

X_single, y_single = load_data('data/tictac_single.txt')
y_single = y_single[:, 0]

X_multi, y_multi = load_data('data/tictac_multi.txt')

## Multilayer Perceptron Classifier

In [8]:
def mlp_clf_train(X, y):
    # Split into training and testing data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)

    # Define and train model
    model = MLPClassifier(max_iter=300)
    model.fit(X_train, y_train)

    # Get accuracy
    accuracy = cross_val_score(model, X_train, y_train, cv=10, scoring="accuracy")
    mean_accuracy = np.mean(accuracy)

    # Get confusion matrix
    y_pred = model.predict(X_test)
    confusion_mtrx = confusion_matrix(y_test, y_pred, normalize="true")

    return mean_accuracy, confusion_mtrx

In [9]:
def print_clf_results(accuracy, confusion_mtrx, dataset_name):
    print(f"Performance of Multilayer Perceptron Classification on {dataset_name}:")
    print("Accuracy = ", accuracy)
    print("Confusion Matrix:")
    print(confusion_mtrx.round(decimals=3)) # Round to 3 decimal places
            
    print("\n")

## Final Dataset

In [10]:
accuracy_final, confusion_mtrx_final = mlp_clf_train(X_final, y_final)
print_clf_results(accuracy_final, confusion_mtrx_final, "Final Dataset")

c:\Users\helar\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\helar\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\helar\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\helar\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\helar\anaconda3\Lib\site-packages\sklearn\neural_network\_multi

Performance of Multilayer Perceptron Classification on Final Dataset:
Accuracy =  0.9869617224880383
Confusion Matrix:
[[0.925 0.075]
 [0.    1.   ]]




c:\Users\helar\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


## Single Dataset

In [11]:
accuracy_single, confusion_mtrx_single = mlp_clf_train(X_single, y_single)
print_clf_results(accuracy_single, confusion_mtrx_single, "Single Dataset")

c:\Users\helar\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\helar\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\helar\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\helar\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\helar\anaconda3\Lib\site-packages\sklearn\neural_network\_multi

Performance of Multilayer Perceptron Classification on Single Dataset:
Accuracy =  0.8715648854961833
Confusion Matrix:
[[0.91  0.012 0.015 0.009 0.034 0.006 0.009 0.    0.003]
 [0.03  0.863 0.018 0.012 0.03  0.018 0.024 0.    0.006]
 [0.021 0.016 0.877 0.037 0.021 0.    0.011 0.011 0.005]
 [0.043 0.    0.009 0.906 0.009 0.    0.026 0.    0.009]
 [0.059 0.01  0.03  0.    0.891 0.    0.005 0.    0.005]
 [0.    0.053 0.    0.    0.    0.908 0.026 0.013 0.   ]
 [0.03  0.04  0.03  0.04  0.    0.    0.848 0.    0.01 ]
 [0.04  0.04  0.    0.06  0.02  0.    0.    0.84  0.   ]
 [0.022 0.022 0.011 0.    0.    0.011 0.    0.    0.933]]




c:\Users\helar\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


# Multilayer Perceptron Regressor