In [40]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict

# Load Datasets

In [41]:
def load_data(file_path):
    A = np.loadtxt(file_path)
    X = A[:, :9]    # Input features
    y = A[:, 9:]    # Output labels
    return X, y

In [42]:
# Load all 3 datasets
X_final, y_final = load_data('../data/tictac_final.txt')
y_final = y_final[:, 0]

X_single, y_single = load_data('../data/tictac_single.txt')
y_single = y_single[:, 0]

X_multi, y_multi = load_data('../data/tictac_multi.txt')

# SVM Classifier

In [51]:
def svm_train(X, y):
    # Split into training and testing data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)

    # Define and train model
    model = SVC(kernel='linear')
    model.fit(X_train, y_train)

    # Get accuracy
    accuracy = cross_val_score(model, X_train, y_train, cv=10, scoring="accuracy")
    mean_accuracy = np.mean(accuracy)

    # Get confusion matrix
    y_pred = model.predict(X_test)
    confusion_mtrx = confusion_matrix(y_test, y_pred)

    return mean_accuracy, confusion_mtrx


In [57]:
def print_results(accuracy, confusion_mtrx, dataset_name):
    print(f"Performance of Linear SVM on {dataset_name}:")
    print("Accuracy = ", accuracy)
    print("Confusion Matrix:")
    print(confusion_mtrx)

## Final Dataset

In [58]:
accuracy_final, confusion_mtrx_final = svm_train(X_final, y_final)
print_results(accuracy_final, confusion_mtrx_final, "Final Dataset")

Performance of Linear SVM on Final Dataset:
Accuracy =  0.9869617224880383
Confusion Matrix:
[[ 61   6]
 [  0 125]]


## Single Dataset

In [59]:
accuracy_single, confusion_mtrx_single = svm_train(X_single, y_single)
print_results(accuracy_single, confusion_mtrx_single, "Single Dataset")

Performance of Linear SVM on Single Dataset:
Accuracy =  0.3662213740458015
Confusion Matrix:
[[323   0   0   0   0   0   0   0   0]
 [ 90  16  29   0  33   0   0   0   0]
 [112   0  43   0  32   0   0   0   0]
 [ 73   6  21   1  16   0   0   0   0]
 [122   0   0   0  80   0   0   0   0]
 [ 41   7  20   0   8   0   0   0   0]
 [ 55   8  20   2  14   0   0   0   0]
 [ 30   9   9   0   2   0   0   0   0]
 [ 56   5  19   0   9   0   0   0   0]]


## Multi Dataset

In [65]:
# TODO: This is prob wrong, idk how to properly train models for this dataset yet
# Create 9 classification models for each output vector
for i in range(9):
    y_data = y_multi[:, i]

    accuracy_multi, confusion_mtrx_multi = svm_train(X_multi, y_data)
    print_results(accuracy_multi, confusion_mtrx_multi, f"Multi Dataset {i}")
    print("\n")

Performance of Linear SVM on Multi Dataset 0:
Accuracy =  0.7631679389312976
Confusion Matrix:
[[988   0]
 [323   0]]


Performance of Linear SVM on Multi Dataset 1:
Accuracy =  0.8213740458015268
Confusion Matrix:
[[1086    0]
 [ 225    0]]


Performance of Linear SVM on Multi Dataset 2:
Accuracy =  0.7646946564885496
Confusion Matrix:
[[998   0]
 [313   0]]


Performance of Linear SVM on Multi Dataset 3:
Accuracy =  0.8227099236641221
Confusion Matrix:
[[1061    0]
 [ 250    0]]


Performance of Linear SVM on Multi Dataset 4:
Accuracy =  0.706679389312977
Confusion Matrix:
[[926   0]
 [385   0]]


Performance of Linear SVM on Multi Dataset 5:
Accuracy =  0.8194656488549619
Confusion Matrix:
[[1077    0]
 [ 234    0]]


Performance of Linear SVM on Multi Dataset 6:
Accuracy =  0.7543893129770991
Confusion Matrix:
[[1021    0]
 [ 290    0]]


Performance of Linear SVM on Multi Dataset 7:
Accuracy =  0.8230916030534351
Confusion Matrix:
[[1069    0]
 [ 242    0]]


Performance of Linear